spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dalda?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '0000'
    hikari:
      autoReconnection: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
  #OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 332607151057-5kifr6ct5r3re0d9i09qhsv47n6pf38a.apps.googleusercontent.com
            client-secret: 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
            scope: profile
app:
  auth:
    tokenSecret: dfa07889d2651d1786427376c6c270b82976e2e0ba8f9f0a7c62f68a02943fe21a99e8cbd48aff8a63951bc06e2b809b9e8d5b81c8f8eaac5d12b71388b95903
    tokenExpiration: 1800000
  oauth2:
    redirectUri: "https://localhost:8080/redirect"

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

cloud:
  aws:
    credentials:
      accessKey: AKIAUZMJJB2EMZG2XA7V
      secretKey: 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
    s3:
      bucket: dalda.img
      dirOriginal: original/
    region:
      static: ap-northeast-2
    stack:
      auto: false